image: node:16

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - npm install
    - echo "NAVIGATOR_URL=https://mitre-atlas.github.io/atlas-navigator" > .env
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  tags:
    - pages
  only:
    - develop
