image: node:16-alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - npm install
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - develop
