image: node:alpine3.13

pages:
  script:
    - npm install
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  tags:
    - docker
<<<<<<< HEAD
  only:
    - main
=======
  when: manual
>>>>>>> origin/develop
